const { validationResult } = require(`express-validator`);
var nodemailer = require('nodemailer');
const transporter = nodemailer.createTransport({
    port: 465,               // true for 465, false for other ports
    host: "smtp.gmail.com",
    auth: {
        user: 'verify.otp.email@gmail.com',
        pass: 'wywjlppnflaeimwc',
    },
    secure: true,
});


const email_send = async (req, res) => {
    let success = false;
    console.log(req.body);
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.status(400).json({ success, errors: errors.array() });
    }
    const { to, subject, message, sender } = req.body;
    if (sender == "user") {
        var name = "Name " + message.name;
        var email = "Email " + message.email;
        var phone = "Phone " + message.phone;
    }
    else {
        var name = "Company Name " + message.name;
        var email = "Company Email " + message.email;
        var phone = "Company Phone " + message.phone;
    }
    const emailData = {
        from: "verify.otp.email@gmail.com",
        to: to,
        subject: subject,
        message: message,
        html: "<body style='background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;'>" +
            "<span class='preheader' style='color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;'>This message is auto generated by Company Name</span>" +
            "<table role='presentation' border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f6f6f6; width: 100%;' width='100%' bgcolor='#f6f6f6'>" +
            "<tr>" +
            "<td style='font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'>&nbsp;</td>" +
            "<td class='container' style='font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; max-width: 580px; padding: 10px; width: 580px; margin: 0 auto;' width='580' valign='top'>" +
            "<div class='content' style='box-sizing: border-box; display: block; margin: 0 auto; max-width: 580px; padding: 10px;'>" +
            "<table role='presentation' class='main' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background: #ffffff; border-radius: 3px; width: 100%;' width='100%'>" +
            "<tr>" +
            "<td class='wrapper' style='font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;' valign='top'>" +
            "<table role='presentation' border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;' width='100%'>" +
            "<tr>" +
            "<td style='font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 15px;'>Hi there,</p>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 15px;'>"+message.text + "</p>" +
            "<table role='presentation' border='0' cellpadding='0' cellspacing='0' class='btn btn-primary' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; box-sizing: border-box; width: 100%;' width='100%'>" +
            "<tbody>" +
            "<tr>" +
            "<td align='left' style='font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;' valign='top'>" +
            "<table role='presentation' border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;'>" +
            "<tbody>" +
            "<tr>" +
            "<td style='font-family: sans-serif; font-size: 14px; vertical-align: top; border-radius: 5px; text-align: center; background-color: #3498db;' valign='top' align='center' bgcolor='#3498db'> <a href='' target='_blank' style='border: solid 1px #3498db; border-radius: 5px; box-sizing: border-box; cursor: pointer; display: inline-block; font-size: 14px; font-weight: bold; margin: 0; padding: 12px 25px; text-decoration: none; text-transform: capitalize; background-color: #3498db; border-color: #3498db; color: #ffffff;'>Thank you for Sending the Query</a> </td>" +
            "</tr>" +
            "</tbody>" +
            "</table>" +
            "</td>" +
            "</tr>" +
            "</tbody>" +
            "</table>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 5px;'>Thanks & Regards.</p>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0;'>" + name + "</p>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0;'>" + email + "</p>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0;'>" + phone + "</p>" +
            "</td>" +
            "</tr>" +
            "</table>" +
            "</td>" +
            "</tr>" +
            "</table>" +
            "<div class='footer' style='clear: both; margin-top: 10px; text-align: center; width: 100%;'>" +
            "<span class='apple-link' style='color: #999999; font-size: 12px; text-align: center;'>Company Name, 3 Abbey Road, San Francisco CA 94102</span>" +
            "</div>" +
            "</div>" +
            "</td>" +
            "<td style='font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'>&nbsp;</td>" +
            "</tr>" +
            "</table>" +
            "</body>",
    };
    transporter.sendMail(emailData, (error, info) => {
        if (error) {
            console.log(error);
        }
        res.status(200).send({ message: "Mail Send", messageId: info.messageId })
    })

};




const email_payment = async (to, transcationId) => {
console.log("Email");
    const emailData = {
        from: "verify.otp.email@gmail.com",
        to: to,
        subject: "Payment have been Successfully Submitted!",
        message: "Congratulation your payment is successfully recorded your transcation id is",
        html: "<body style='background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;'>" +
            "<span class='preheader' style='color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;'>This message is auto generated by Company Name</span>" +
            "<table role='presentation' border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f6f6f6; width: 100%;' width='100%' bgcolor='#f6f6f6'>" +
            "<tr>" +
            "<td style='font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'>&nbsp;</td>" +
            "<td class='container' style='font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; max-width: 580px; padding: 10px; width: 580px; margin: 0 auto;' width='580' valign='top'>" +
            "<div class='content' style='box-sizing: border-box; display: block; margin: 0 auto; max-width: 580px; padding: 10px;'>" +
            "<table role='presentation' class='main' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background: #ffffff; border-radius: 3px; width: 100%;' width='100%'>" +
            "<tr>" +
            "<td class='wrapper' style='font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;' valign='top'>" +
            "<table role='presentation' border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;' width='100%'>" +
            "<tr>" +
            "<td style='font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 15px;'>Hi there,</p>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 15px;'>"+message.text + "</p>" +
            "<table role='presentation' border='0' cellpadding='0' cellspacing='0' class='btn btn-primary' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; box-sizing: border-box; width: 100%;' width='100%'>" +
            "<tbody>" +
            "<tr>" +
            "<td align='left' style='font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;' valign='top'>" +
            "<table role='presentation' border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;'>" +
            "<tbody>" +
            "<tr>" +
            "<td style='font-family: sans-serif; font-size: 14px; vertical-align: top; border-radius: 5px; text-align: center; background-color: #3498db;' valign='top' align='center' bgcolor='#3498db'> <a href='' target='_blank' style='border: solid 1px #3498db; border-radius: 5px; box-sizing: border-box; cursor: pointer; display: inline-block; font-size: 14px; font-weight: bold; margin: 0; padding: 12px 25px; text-decoration: none; text-transform: capitalize; background-color: #3498db; border-color: #3498db; color: #ffffff;'>"+ transcationId +"</a> </td>" +
            "</tr>" +
            "</tbody>" +
            "</table>" +
            "</td>" +
            "</tr>" +
            "</tbody>" +
            "</table>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 5px;'>Thanks & Regards.</p>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0;'>" + "TomKings Puppies" + "</p>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0;'>" + "puppie@gmail.com" + "</p>" +
            "<p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0;'>" + "1234567890" + "</p>" +
            "</td>" +
            "</tr>" +
            "</table>" +
            "</td>" +
            "</tr>" +
            "</table>" +
            "<div class='footer' style='clear: both; margin-top: 10px; text-align: center; width: 100%;'>" +
            "<span class='apple-link' style='color: #999999; font-size: 12px; text-align: center;'>Company Name, 3 Abbey Road, San Francisco CA 94102</span>" +
            "</div>" +
            "</div>" +
            "</td>" +
            "<td style='font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'>&nbsp;</td>" +
            "</tr>" +
            "</table>" +
            "</body>",
    };
    console.log("Email Sending..");
    transporter.sendMail(emailData, (error, info) => {
        if (error) {
            console.log(error);
        }
        console.log("Email Send");
        // res.status(200).send({ message: "Mail Send", messageId: info.messageId })
    })

};


module.exports = {
    email_send,
    email_payment
}